### PR TITLE
Text Options Menu

### PR DESCRIPTION
**Pull request by bucketteOfIvy**
The text options menu! 

I expect this to need some changes in code review, but also the easiest way to get feedback on those changes / determine exactly what they are is to make a pull request, so here be the request. The menu should successfully cause a bit of chaos for the user, and is intended to evoke a sense of overwhelm. 

As future potential additions to this, I sorta want to add a sound element to it to increase the overwhelm factor (since overwhelm is frequently a multi-sensory experience), but I'd like to do that through a dedicated library for this project (such as C2D), so I'm stalling on that addition to this menu for now. If such a library is introduced (by myself or someone else) I'll likely open an issue about updating this module with said feature.

### CODE REVIEW

**Comment by bucketteOfIvy** [comment]
Looking through the commits to this branch, I just realized that the commits make it seem like the "doop" tool is included — that was actually purged as part of the dual commits 2b823b2 and 147874c, as it was made just for testing purposes.

**Comment by nbriz** [comment]
I've downloaded && tested this && love it :)

i'm still looking through the remaining PRs && giving everyone's code a close read (&& need to inspect this one a little closer), but one thing i noticed here is that there's a lot of redundant code in ur CSS animations. what if u replaced the functionality u've written in all those CSS animations with a simpler/single JavaScript DOM function?

**Comment by bucketteOfIvy** [comment]
> I've downloaded && tested this && love it :)
> 
> i'm still looking through the remaining PRs && giving everyone's code a close read (&& need to inspect this one a little closer), but one thing i noticed here is that there's a lot of redundant code in ur CSS animations. what if u replaced the functionality u've written in all those CSS animations with a simpler/single JavaScript DOM function?

Worked on this! Repetitive animation stuff is now generated via some loops. Which also resulted in more overwhelm, and an easy way for other things to interact with the amount of overwhelm generated.

**Comment by nbriz** [comment]
great job cleaning this up!

before i merge this, what did u end up deciding about the left over effect? when u switch back to one of the other options it keeps that gradient background. i remember u mentioned that u had tried to get rid of it but kept running into issues. If u did want to remove it after switching back, here's what i'd do:

1. create a state property (for example `bg`) which holds a reference to the interval  `setBackgroundRainbow` interval, so that [in this spot](https://github.com/bucketteOfIvy/paintArtware1.0/blob/c30620b99e3ae7d5576db14c4aebbeb8a46c8da5/js/options/textOptions.js#L63) u could do something like this:

```js
window.options.textOptions.bg = setInterval(setBackgroundRainbow, 100, tooloptions, colors)
```
2. create a new method (maybe we call this "unload") in the textOptions object which handles returning things back to normal, something like:
```js
state: {
  text: 'doop!',
  bg: null,
  numberOfHorrors: 20
},
unload: function () {
  // this part stops the interval loop
  clearInterval(window.options.textOptions.bg)
  // this part reverts the tool-options background
  document.querySelector('#tool-options').style.background = 'none'
},
run: function () {
  //... 
}
```

now we can call `window.options.textOptions.unload()` to return things to normal. the next question would be... when/where do we call that? i have a few ideas, but before i dive any deeper want to hear ur thoughts. do u want things to go back to normal? or are u intentionally leaving that rainbow bg hanging around?

**Comment by bucketteOfIvy** [comment]
Yay! I'm glad to hear it looks good. 

With regards to the persistent rainbow suffering, I think I decided that it may as well stay. Thematically it makes a bit of sense anyway — overwhelm does have a bit of an after effect that can take a while to get over, even once you've left the stimuli that caused it (which is, in this case, the text options menu itself). 

Although I do really appreciate the ideas for getting rid of the menu, especially since I failed to do so for so long.

**Pull request merged**
