### PR TITLE
hacker text tool

### PR DESCRIPTION
**Pull request by lnealer**

### CODE REVIEW

**Comment by nbriz** [comment]
this is so rad!

i'm nearly ready to merge this as is, but wanted to suggest a potential rewrite if u're up for it (it's cool either way). this is a great concept, && the way u handled it (creating an array of strings that mirror the actual lines of code) is great... but what if instead of pulling from this Array of "fake code", it pulled from the actual source code itself... what if it wasn't only this file, but every file in the app?  if u think that be cool, the process would look something like this:

load the file's source code as a string using the browser's [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). I made a couple of tutorials on this API which [u can access here](https://netart.rocks/uchicago/netart2/epilogue.html) (the two links that say "the Fetch API") if u're curious to learn the ins/outs of this API. The Fetch API returns a special object known as a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) which is one of the many ways to handle "asynchronous" code in JavaScript (code that runs on the side while the rest of ur program executes). Writing asynchronous code can be confusing if u've never done it before (all stuff i explain in those tutorials i linked to) but there are [ways of writing it](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) that make it function more like traditional "synchronous" code, which is what i would recommend. the steps would be as follows:

1. add the special keyword `async` just before the word `function` to your `mousemove` event. this will allow us to write asynchronous code synchronously inside the function, should look like:
```js
mousemove: async function (e) {
```
2. then inside the function write the following:
```js
// this line loads the file's raw data
const res = await window.fetch('/js/tools/hackerText.js')
// this line converts it into a string
const string = await res.text()
// this line turns that string into an Array,
// by splitting it at each line break "\n"
const codeSnippets = string.split('\n')
```

now "codeSnippets" will actually be pulling from ur tool's actual souce code. if later u make edits to that file, u won't need to update that Array manually. also, u might be able to imagine ways of expanding on the code above so that u not only load data from this tool but from any/all files in the app :)

**Comment by lnealer** [comment]
That sounds very cool, I'll definitely give it a try!

**Comment by lnealer** [comment]
@nbriz I think I figured it out, but let me know what you think!

**Comment by nbriz** [comment]
this is fantastic Leandra, nice to see u relocated that helper function out of the global scope && into the tool! there are a couple other edits i'd suggest before we merge this:

1. the way u're using the lineWidth to change the font size here is very clever, but now that @bucketteOfIvy  has updated the `canvas2d.js` library ([see updated docs](https://github.com/net-art-uchicago/paintArtware1.0/blob/main/docs/C2D.md)) with new properties for `C2D.fontSize`, `C2D.fontFamily`, etc. it might be best to interact with these directly [instead of the way u're doing it here](https://github.com/lnealer/paintArtware1.0/blob/e7882e8aafdb225655acc8d2649570802d68c694/js/tools/hackerText.js#L43-L45).
This way, if/when someone creates new option parameters for these it can also be used to control this brush. that said, if u prefer this method && have a good argument for it then we can leave it like this (using lineWidth), but u'll need to reset the canvas's original fontSize && fontFamily back after making ur mark.
Remember how we discussed in class how anyone working on tools that changed the canvas fill or stroke colors would have to store the current colors in local state so they could use those values to reset the global colors on mouse up? u'll need to do something similar w/the font properties (to avoid potentially conflicting w/other font related tools/options/etc)


2. the tool seems to be running fine, so this next point is only a suggestion (feel free to disregard this one), but at the moment everytime the user presses their mouse down u're reading from all the js files && creating a new codeSnippets Array. seeing as how these files won't change after the app loads, there's really no need to create this array more than once. we can rewrite this to be more "efficient" by checking to see if the `codeSnippets` array has data in it && [only running this code *if* it's empty](https://github.com/lnealer/paintArtware1.0/blob/e7882e8aafdb225655acc8d2649570802d68c694/js/tools/hackerText.js#L16-L27).


3. last tiny thing, u've got [a line break here](https://github.com/lnealer/paintArtware1.0/blob/e7882e8aafdb225655acc8d2649570802d68c694/js/tools/hackerText.js#L55) which violates [our code style](https://github.com/net-art-uchicago/paintArtware1.0/wiki/collaborative-workflow#working-on-your-task), did u [install the standardJS linter on ur editor](https://standardjs.com/#are-there-text-editor-plugins)? it should have caught this + warned u about it?

**Comment by lnealer** [comment]
I added the changes! The linter doesn't throw an error for that linebreak for some reason? But I got rid of that too

**Comment by nbriz** [comment]
looks great! merging now!

**Pull request merged**
