### PR TITLE
Smiley Face Tool and Change Colors function

### PR DESCRIPTION
**Pull request by silviachie**

### CODE REVIEW

**Comment by silviachie** [comment]
This code adds a smiley face tool which responds to the 2 colors chosen and stroke size.
Also added a change_color function which allows colors to be assigned to stroke and fill.

**Comment by nbriz** [comment]
Hey Silvia, the brush works great! but there are lots style issues w/the way u've written ur code, it violates [our code style](https://github.com/net-art-uchicago/paintArtware1.0/wiki/collaborative-workflow#working-on-your-task), did u [install the standardJS linter on ur editor](https://standardjs.com/#are-there-text-editor-plugins)? it should have caught these issues + warned u about it?

also, it looks like u might not have comitted ur icon (i'm not seeing it in ur [images folder](https://github.com/silviachie/paintArtware1.0/tree/main/images))

**Comment by silviachie** [comment]
Hello! I have updated the smile image to images and changed the style of the codes to match JS standard

**Comment by nbriz** [comment]
this looks great! there's a tiny conflict in the `settings.json` file (but i can resolve that as i merge it)

**Pull request merged**
