### PR TITLE
PR for corresponding paintText function issue

### PR DESCRIPTION
**Pull request by dliGH**

### CODE REVIEW

**Comment by nbriz** [comment]
this is such a cool concept!

...but at the moment everything i type just looks grey :(

i wonder if there's a way to modify the algorithm u've written so that it produces some more interesting results? ...or maybe i'm projecting too much of my own sensibilities here? what do u think?

**Comment by nbriz** [comment]
hey @dliGH  what's the status of this PR? have u had a chance to update the `paintText.js` function yet? did u get it to work with file uploads? 

also don't forget u need to update the `js/settings.json` && include "paintText" in the `functions` Array.

it also seems like their are some merge conflict markers in the `index.html` file, to try to clean that file up (should look like [the one on the main repo](https://github.com/net-art-uchicago/paintArtware1.0/blob/main/index.html))

**Comment by dliGH** [comment]
@nbriz Still working on reimplementing the function in a way to include the file uploads rather than just text input.  I should have everything done before the start of class tomorrow.  Will update the files as necessary and make sure there are no conflicts.

**Comment by dliGH** [comment]
@nbriz Finished! Seems much more interesting.

**Comment by nbriz** [comment]
nice!
u still haven't addressed the issue with the `index.html` page though, u need to remove the merge conflict markers below (lines 51-53, 55) 
https://github.com/net-art-uchicago/paintArtware1.0/blob/0d79099e70fc2463f8bd51e6e0a4bc39ea2786cc/index.html#L50-L56

**Pull request merged**
