### PR TITLE
Implementing pixel filter

### PR DESCRIPTION
**Pull request by dliGH**
Completing the Pixel Art filter issue

### CODE REVIEW

**Comment by nbriz** [comment]
Ah yes, this is a much faster/easier way to pixelate rather than trying to algorithmically manipulating all the pixels, good find! Only issue right now is that u're violating [our code style](https://github.com/net-art-uchicago/paintArtware1.0/wiki/collaborative-workflow#working-on-your-task), did u [install the standardJS linter on ur editor](https://standardjs.com/#are-there-text-editor-plugins)? it should have caught this + warned u about it? (when u do, don't forget to add the `/* global C2D */` comment at the top of ur file so that the linter is aware of the `C2D` global variable && doesn't yell at u about it)

**Comment by nbriz** [comment]
perfect! merging now!

**Comment by dliGH** [comment]
Did install the linter in the editor but for some reason it wasn't yelling at me. Figured out how to run the auto-formatting so things should look ok now!

**Comment by nbriz** [comment]
looks like the auto-formater might have also made some [unintentional changes to the Maths.js](https://github.com/net-art-uchicago/paintArtware1.0/pull/29/files#diff-26e304e817b640e530c0a8261ca67e2bdcccda087bf16d1d8d28b5c6762503cd) library (^_^) but that's cool, we can keep it :) merging now!

**Pull request merged**
